---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30021

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
      - name: api
        image: api:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80