---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30021
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-volume-claim
  labels:
    app: api
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: api-volume
  labels:
    type: local
    app: api
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
      - name: api
        image: gcr.io/isa-mrs-345117/api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 128m
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_CONNECTION
          value: Server=postgres;Port=5432;Database=api;User ID=admin;Password=admin
        volumeMounts:
        - mountPath: /data/images
          name: api-volume-claim
      volumes:
      - name: api-volume-claim
        persistentVolumeClaim:
          claimName: api-volume-claim