// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Infrastructure;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220406093043_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Core.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Images")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfReviews")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Businesses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Business");
                });

            modelBuilder.Entity("api.Core.Models.Loyalty", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("LoyaltyLevels");
                });

            modelBuilder.Entity("api.Core.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("End");

                    b.HasIndex("Start");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("api.Core.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("api.Core.Models.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Tax");
                });

            modelBuilder.Entity("api.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("LevelName")
                        .HasColumnType("text");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("LevelName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Core.Models.Adventure", b =>
                {
                    b.HasBaseType("api.Core.Models.Business");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<double>("CancellationFeePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("Adventure_CancellationFeePercentage");

                    b.HasDiscriminator().HasValue("Adventure");
                });

            modelBuilder.Entity("api.Core.Models.Boat", b =>
                {
                    b.HasBaseType("api.Core.Models.Business");

                    b.Property<double>("CancellationFeePercentage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Boat");
                });

            modelBuilder.Entity("api.Core.Models.Cabin", b =>
                {
                    b.HasBaseType("api.Core.Models.Business");

                    b.HasDiscriminator().HasValue("Cabin");
                });

            modelBuilder.Entity("api.Core.Models.Business", b =>
                {
                    b.HasOne("api.Core.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("api.Core.Models.User", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId");

                    b.OwnsOne("api.Core.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("BusinessId");

                            b1.ToTable("Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.OwnsOne("api.Core.Models.Money", "PricePerUnit", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .HasColumnType("text");

                            b1.Property<string>("Symbol")
                                .HasColumnType("text");

                            b1.HasKey("BusinessId");

                            b1.ToTable("Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.OwnsMany("api.Core.Models.Service", "Services", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.HasKey("BusinessId", "Id");

                            b1.ToTable("Businesses_Services");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");

                            b1.OwnsOne("api.Core.Models.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("ServiceBusinessId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ServiceId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("text");

                                    b2.Property<string>("Symbol")
                                        .HasColumnType("text");

                                    b2.HasKey("ServiceBusinessId", "ServiceId");

                                    b2.ToTable("Businesses_Services");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceBusinessId", "ServiceId");
                                });

                            b1.Navigation("Price");
                        });

                    b.OwnsMany("api.Core.Models.Rule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Allowed")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.HasKey("BusinessId", "Id");

                            b1.ToTable("Rule");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.OwnsMany("api.Core.Models.Slot", "Availability", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Available")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("BusinessId", "Id");

                            b1.ToTable("Slot");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Owner");

                    b.Navigation("PricePerUnit");

                    b.Navigation("Rules");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("api.Core.Models.Reservation", b =>
                {
                    b.HasOne("api.Core.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId");

                    b.HasOne("api.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("api.Core.Models.Complaint", "Complaint", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Answer")
                                .HasColumnType("text");

                            b1.Property<bool>("Answered")
                                .HasColumnType("boolean");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Complaints");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("api.Core.Models.Payment", "Payment", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<double>("DiscountPercentage")
                                .HasColumnType("double precision");

                            b1.Property<double>("TaxPercentage")
                                .HasColumnType("double precision");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");

                            b1.OwnsOne("api.Core.Models.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("PaymentReservationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("text");

                                    b2.Property<string>("Symbol")
                                        .HasColumnType("text");

                                    b2.HasKey("PaymentReservationId");

                                    b2.ToTable("Reservations");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentReservationId");
                                });

                            b1.Navigation("Price");
                        });

                    b.OwnsOne("api.Core.Models.Report", "Report", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsApproved")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Penalize")
                                .HasColumnType("boolean");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsMany("api.Core.Models.Service", "Services", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.HasKey("ReservationId", "Id");

                            b1.ToTable("Reservations_Services");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");

                            b1.OwnsOne("api.Core.Models.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("ServiceReservationId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ServiceId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("text");

                                    b2.Property<string>("Symbol")
                                        .HasColumnType("text");

                                    b2.HasKey("ServiceReservationId", "ServiceId");

                                    b2.ToTable("Reservations_Services");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceReservationId", "ServiceId");
                                });

                            b1.Navigation("Price");
                        });

                    b.Navigation("Business");

                    b.Navigation("Complaint");

                    b.Navigation("Payment");

                    b.Navigation("Report");

                    b.Navigation("Services");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Core.Models.Review", b =>
                {
                    b.HasOne("api.Core.Models.Business", "Business")
                        .WithMany("Reviews")
                        .HasForeignKey("BusinessId");

                    b.HasOne("api.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Core.Models.User", b =>
                {
                    b.HasOne("api.Core.Models.Business", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("BusinessId");

                    b.HasOne("api.Core.Models.Loyalty", "Level")
                        .WithMany()
                        .HasForeignKey("LevelName");

                    b.OwnsOne("api.Core.Models.DeletionRequest", "DeletionRequest", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Answer")
                                .HasColumnType("text");

                            b1.Property<bool>("Approved")
                                .HasColumnType("boolean");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("api.Core.Models.Penalty", "Penalty", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("api.Core.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("DeletionRequest");

                    b.Navigation("Level");

                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("api.Core.Models.Boat", b =>
                {
                    b.OwnsOne("api.Core.Models.BoatCharacteristics", "Characteristics", b1 =>
                        {
                            b1.Property<Guid>("BoatId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BHP")
                                .HasColumnType("integer");

                            b1.Property<int>("Engines")
                                .HasColumnType("integer");

                            b1.Property<int>("Length")
                                .HasColumnType("integer");

                            b1.Property<int>("Seats")
                                .HasColumnType("integer");

                            b1.Property<int>("TopSpeed")
                                .HasColumnType("integer");

                            b1.HasKey("BoatId");

                            b1.ToTable("Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BoatId");
                        });

                    b.OwnsOne("api.Core.Models.BoatEquipment", "Equipment", b1 =>
                        {
                            b1.Property<Guid>("BoatId")
                                .HasColumnType("uuid");

                            b1.Property<List<string>>("Additional")
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("Navigational")
                                .HasColumnType("text[]");

                            b1.HasKey("BoatId");

                            b1.ToTable("Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BoatId");
                        });

                    b.Navigation("Characteristics");

                    b.Navigation("Equipment")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Core.Models.Cabin", b =>
                {
                    b.OwnsMany("api.Core.Models.Room", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("CabinId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Beds")
                                .HasColumnType("integer");

                            b1.HasKey("CabinId", "Id");

                            b1.ToTable("Room");

                            b1.WithOwner()
                                .HasForeignKey("CabinId");
                        });

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("api.Core.Models.Business", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("api.Core.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
